import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersMeRouter from "./users-me";
import usersRouter from "./users";
import userFollowsRouter from "./user-follows";
import soloRoundRouter from "./solo-round";
import tripsRouter from "./trips";
import playersRouter from "./players";
import roundsRouter from "./rounds";
import scoresRouter from "./scores";
import scrambleScoresRouter from "./scramble-scores";
import leaderboardRouter from "./leaderboard";
import coursesRouter from "./courses";
import groupsRouter from "./groups";
import roundKudosRouter from "./round-kudos";
import roundCommentsRouter from "./round-comments";
import roundSocialRouter from "./round-social";
import feedRouter from "./feed";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersMeRouter);
router.use(usersRouter);
router.use(userFollowsRouter);
router.use(soloRoundRouter);
router.use(tripsRouter);
router.use(playersRouter);
router.use(roundsRouter);
router.use(scoresRouter);
router.use(scrambleScoresRouter);
router.use(leaderboardRouter);
router.use(coursesRouter);
router.use(groupsRouter);
router.use(roundKudosRouter);
router.use(roundCommentsRouter);
router.use(roundSocialRouter);
router.use(feedRouter);

export default router;
